[features]
seeds = false

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet.json"

[workspace]
members = [
  "candy-guard",
  "candy-machine-core",
  "macro"
]